### ISSUE TITLE
Lilybin on Android phone

### ISSUE THREAD

**Issue by ChristopheRichard** [trevordixon/LilyBin#13]
Hi,

Thanks for this great tool, I can work with Lilypond everywhere. But i have a problem on my 5 inch Android phone with Chrome Browser : I've no access to the code panel because of the size of the preview panel that I cannot reduce . The best will be to have a button at right to hide/show preview panel and a button at left to hide/show dropbox panel.

Christophe

**Comment by samusz** [comment]
This bug is also true on Firefox for android.  It renders the bin unusable as copy and paste also do not work (tm). Thanks for the great work.

**Comment by scottlinux** [comment]
lilybin uses cursor: e-resize to resize the code window which is not available on mobile browsers. I'll dig around for options.
