### ISSUE TITLE
Add tooltip recommending user to use `\midi{}`

### ISSUE THREAD

**Issue by TimothyGu** [trevordixon/LilyBin#14]
```
$ curl http://lilybin.com/downloadMidi?id=re99gm && echo
Error: ENOENT, stat '/var/www/lilybin.com/render/re99gm.midi'
```

[Only PNG and PDF](https://github.com/trevordixon/LilyBin/blob/master/server.js#L169) seem to be generated.

**Comment by trevordixon** [comment]
If I remember correctly, and unless something has changed, LilyPond will automatically make a MIDI file if the score itself directs it; it doesn't have to be specified when invoking the LilyPond process.

Ideally the MIDI download button would only be presented if there was a MIDI file to download.

**Comment by TimothyGu** [comment]
Yes I found out that LilyBin itself doesn't do anything to help support MIDI. One has to manually add `\midi{}` to make it work.

> Ideally the MIDI download button would only be presented if there was a MIDI file to download.

Or we can use a tooltip to tell the user to add `\midi{}` if the download fails.

**Comment by trevordixon** [comment]
Great idea.
