### ISSUE TITLE
Switch to Bootstrap

### ISSUE THREAD

**Issue by TimothyGu** [trevordixon/LilyBin#19]
I have to say that the LilyBin frontend as-is is pretty impressive without the use of any external style library. However, I think it is time to think about using a well-maintained responsive CSS framework like Bootstrap or even Materialize. The grid system in both frameworks might be a little bit easier to hack on and maintain than the current split bar approach, which TBH feels really last decade-ish. It will also make a responsive version easier.

**Comment by scottlinux** [comment]
This is a great idea. The sliding split frame has been problematic for mobile devices.

**Comment by trevordixon** [comment]
Yep, it needs a redesign.
