### ISSUE TITLE
Use SVG rather than PNG

### ISSUE THREAD

**Issue by TimothyGu** [trevordixon/LilyBin#20]
Reason is pretty obvious.

**Comment by trevordixon** [comment]
I'd planned on using https://mozilla.github.io/pdf.js/ to show the rendered PDF, but SVG might be a better choice.

With regard to SVG output, http://www.lilypond.org/doc/v2.18/Documentation/usage/command_002dline-usage says, "This creates a single SVG file, without embedded fonts, for every page of output. It is recommended to install the Century Schoolbook fonts, included with your LilyPond installation, for optimal rendering."

It might be a nightmare trying to get the necessary fonts to the user (also consider licensing issues). If SVG proves to be tricky, try PDF.

**Comment by TimothyGu** [comment]
I have considered PDF.js, but its API seems to be fairly convoluted, while we can reuse the corrent zooming routins for SVG. Plus PDF might prove to be larger than SVG (haven't checked).

For the font issue, the page you referenced says: "There is also an option `svg-woff` (below) for use of woff font files in the SVG backend." Not sure if that would satisfy our requirements.

**Comment by TimothyGu** [comment]
Figured out a way to do SVG stuff:

1. <s>Output SVG</s> [Done](https://github.com/TimothyGu/LilyBin/commit/daa3f047162aa3e1d56195dcfc8f9ed28fd34767)
2. Add web fonts for Century Schoolbook L
3. Move to [svg-pan-zoom](https://github.com/ariutta/svg-pan-zoom). Why? Currently the SVG is loaded with `<img>`, which unfortunately doesn't work with `@font-face` in parent HTML/CSS. `<svg>` in HTML works however, so does rewriting SVG to add CSS, which is tricky. Preview.js doesn't work with `<svg>`, and I am not in the mood of wrestling with it.
