### ISSUE TITLE
Remove MongoDB dependency

### ISSUE THREAD

**Issue by trevordixon** [trevordixon/LilyBin#21]
MongoDB is way too heavy for our needs and complicates installation. Switch to either NeDB (easiest, almost API-compatible) or SQLite (more reliable?).

**Comment by TimothyGu** [comment]
I don't think MongoDB is any heavier than SQL. NeDB might complicate session handling (i.e. Dropbox).

The only DB I would ever consider switching to is probably Redis, but its installation process is no less complicated than MongoDB IMO.

**Comment by trevordixon** [comment]
Done with https://github.com/trevordixon/LilyBin/commit/ac3d2ddf2520e8835f2b4a9bc52991a52da19cbe.

Switched to LevelDB, an embedded key value store.
