### ISSUE TITLE
Share should not give unsaved link

### ISSUE THREAD

**Issue by eugenecormier** [trevordixon/LilyBin#31]
A couple of times last year, a student entered code to lilybin.com and clicked the share link and emailed me a link to: lilybin.com/
I know this is user stupidity, but I think if someone clicks the 'share' button, it should do a save and provide the link to the currently saved code

**Comment by TimothyGu** [comment]
In the latest master version of lilybin.com, the share button has been removed. A user should just copy paste the URL now.

**Comment by eugenecormier** [comment]
great! thanks
