### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by eugenecormier** [trevordixon/LilyBin#32]
there are times when I'm scratch-padding on lilybin.com and I remove code to test, only to forget that there is no quick easy way to get the code back (unless I remember to do a ctrl+x ctrl+v).
Every editor under the sun has an undo feature, maybe lilybin should too

**Comment by TimothyGu** [comment]
Ctrl+Z

**Comment by eugenecormier** [comment]
'button' .... my students aren't all that smart, it would be nice to have a button

**Comment by TimothyGu** [comment]
True.

**Comment by eugenecormier** [comment]
when I say 'my students' I actually meant me lol. If I don't see the button, I assumed ctrl+z wouldn't work
