### ISSUE TITLE
Run LilyPond inside a container

### ISSUE THREAD

**Issue by trevordixon** [trevordixon/LilyBin#35]
> When lilypond is invoked with `--safe-mode`, TeX and PostScript file output is disallowed, and lilypond-bin is invoked with `--safe-mode`, the user's Guile expressions are evaluated in a safe environment and file inclusion is not allowed.

**Comment by scottlinux** [comment]
This is a good idea as one could potentially do anything with scheme.

**Comment by trevordixon** [comment]
Even better, we should run LilyPond inside a container.

**Comment by TimothyGu** [comment]
I assume this is related with the current lilybin downtime. I'm not sure if container is the right solution. People who want to bring the site down can still destroy the container, and setting up a new one takes time nevertheless.

**Comment by trevordixon** [comment]
Maybe https://github.com/chris-rock/docker-exec.

Each preview preparation would happen inside a new, clean Docker container.

**Comment by trevordixon** [comment]
http://hmarr.com/2013/oct/16/codecube-runnable-gists/

**Comment by TimothyGu** [comment]
That looks doable.

**Comment by scottlinux** [comment]
I will also investigate the --jail option that lilypond can do to see if it is feasible with lilybin.

http://www.lilypond.org/doc/v2.18/Documentation/usage/command_002dline-usage#basic-command-line-options-for-lilypond

**Comment by trevordixon** [comment]
Good idea. I've started work on the Docker stuff. We'll go with whichever ends up less complicated.

**Comment by trevordixon** [comment]
https://github.com/trevordixon/LilyBin/tree/docker (work in progress)

Works with Docker. (You'll have to change hard coded Docker config in https://github.com/trevordixon/LilyBin/blob/docker/lib/lilypond.js#L8-L15)

To test, install Docker, then run `docker build .` in the LilyBin directory. That will create a Docker image according to the included Dockerfile with two versions of LilyPond installed.

(If we do this, it might be cool to have the Dockerfile download *all* (or at least the last few) versions of LilyPond from http://download.linuxaudio.org/lilypond/binaries/linux-64/ and let people compile with lots of different versions.)

**Comment by trevordixon** [comment]
TODO:

- [ ] Delete https://github.com/trevordixon/LilyBin/blob/docker/server.js#L6
- [ ] Use Docker for version check https://github.com/trevordixon/LilyBin/blob/docker/server.js#L197-L206
- [ ] Use config.json for Docker config https://github.com/trevordixon/LilyBin/blob/docker/lib/lilypond.js#L8
- [ ] Make it still work without Docker for easier development?
