### ISSUE TITLE
Download MIDI icon is tiny on rMBP

### ISSUE THREAD

**Issue by trevordixon** [trevordixon/LilyBin#50]
Not a problem on an iMac. I assume it has to do with the "retina" part.

![screen shot 2015-06-03 at 8 58 41 am](https://cloud.githubusercontent.com/assets/1253245/7964842/d823787c-09ce-11e5-9dd2-3d5cb8412ca6.png)

**Comment by TimothyGu** [comment]
That's weird… even iOS displays that correctly
