### ISSUE TITLE
LilyBin unstable version out of date

### ISSUE THREAD

**Issue by scottlinux** [trevordixon/LilyBin#75]
The current unstable version on LilyBin appears to be 2.19.38, a bit out of date.

I'm not sure if the update script is not running or something else?

**Comment by trevordixon** [comment]
It's always been a manual process to update. I can't think of a really easy way to automate it. Thanks for the reminder to update it. I'll do it today or tomorrow.

**Comment by TimothyGu** [comment]
I've just pushed 2.19.48 to AWS. I've also updated the Node.js runtime on Lambda so that 4.3 is used instead of 0.10.
