### ISSUE TITLE
Dropbox support not working?

### ISSUE THREAD

**Issue by wbajzek** [trevordixon/LilyBin#83]
Hi. I'm playing with LilyBin for the first time. I tried saving to dropbox, and it seemed to work, but the file never showed up in my dropbox. I realize this might be a problem with dropbox, but do you think you could give it a try?

**Comment by TimothyGu** [comment]
Seems to be working here...

**Comment by wbajzek** [comment]
Oh, hmm. It works for me in Firefox but not in Chrome. Both are up to date on my MacBook. I assume it's a problem with dropbox.
